name: Maven Build
description: Build Maven project with revision from file
inputs:
  java-version:
    description: Java version
    required: false
    default: '21'
  distribution:
    description: JDK distribution
    required: false
    default: 'temurin'
  revision-file:
    description: Path to file with revision
    required: false
    default: 'release.version'
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.distribution }}
        java-version: ${{ inputs['java-version'] }}
        cache: maven
    - name: Read revision
      id: rev
      shell: bash
      run: |
        set -euo pipefail
        file="${{ inputs['revision-file'] }}"
        [[ -s "$file" ]] || { echo "Error: '$file' missing or empty."; exit 1; }
        REV="$(tr -d ' \r\n' < "$file")"
        echo "rev=$REV" >> "$GITHUB_OUTPUT"
    - name: Build
      shell: bash
      run: mvn -B -ntp -Drevision="${{ steps.rev.outputs.rev }}" verify