name: Qodana Scan
description: Run Qodana in PR mode
inputs:
  qodana-token:
    description: Qodana Cloud token
    required: true
  post-pr-comment:
    description: Whether to post PR comment
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Qodana Scan
      uses: JetBrains/qodana-action@v2025.2
      env:
        QODANA_TOKEN: ${{ inputs.qodana-token }}
      with:
        pr-mode: true
        use-caches: true
        use-annotations: true
        post-pr-comment: ${{ inputs['post-pr-comment'] }}
        upload-result: false
        push-fixes: 'none'